# Basic Tensor Operations

In [2]:
import numpy as np
import tensorly as tl
from tensorly.testing import assert_array_equal

A tensor is just a numpy array

In [3]:
tensor = tl.tensor(np.arange(24).reshape((3, 4, 2)))
print(format(tensor))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


This tensor can be seen as $3$ numpy arrays of dimension $4 \times 2 $

Unfolding a tensor is easy

In [4]:
for mode in range(tensor.ndim):
    print(f'Unfolding tensor along mode {mode}:')
    print(format(tl.unfold(tensor, mode)))
    

Unfolding tensor along mode 0:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
Unfolding tensor along mode 1:
[[ 0  1  8  9 16 17]
 [ 2  3 10 11 18 19]
 [ 4  5 12 13 20 21]
 [ 6  7 14 15 22 23]]
Unfolding tensor along mode 2:
[[ 0  2  4  6  8 10 12 14 16 18 20 22]
 [ 1  3  5  7  9 11 13 15 17 19 21 23]]


Re-Folding is also easy

In [5]:
for mode in range(tensor.ndim):
    print(f'Folding tensor along mode {mode}:')
    print(format(tl.fold(tl.unfold(tensor, mode), mode, tensor.shape)))

Folding tensor along mode 0:
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
Folding tensor along mode 1:
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
Folding tensor along mode 2:
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
