# T1.1 Diagrammatic Notation

Tensors are multi-dimensional arrays of real or complex numbers.

In [3]:
import numpy as np

# let's initalize some tensors

# tensor with randomly generated entries, order 3, dims 2x3x4
A = np.random.rand(2,3,4)

display(A)

# identity tensor, order 3, dims 3x3x3
I = np.eye(3)

display(I)

# identity matrix, order 2, dims: 5x5
B = np.eye(5,5)

display(B)

# tensor of 1s, order 4, dims 2x4x2x4
C = np.ones((2,4,2,4))

display(C)

# matrix of 0s, order 2, dims 3x5
D = np.zeros((3,5))

display(D)

# initialize complex random tensor
E = np.random.rand(2,3,4) + 1j*np.random.rand(2,3,4)

display(E)

array([[[0.14135046, 0.56905032, 0.94774389, 0.45106705],
        [0.69532777, 0.19925796, 0.32014724, 0.04635711],
        [0.73315465, 0.40150477, 0.77497212, 0.63223962]],

       [[0.07929235, 0.87857317, 0.43597555, 0.91773817],
        [0.74919841, 0.51353032, 0.85002298, 0.8166278 ],
        [0.17037123, 0.10911028, 0.0718095 , 0.55230118]]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[[0.54085877+0.68811485j, 0.06902786+0.12996811j,
         0.09416707+0.53022381j, 0.83781112+0.3986796j ],
        [0.98168992+0.96327393j, 0.40709416+0.58750945j,
         0.59071173+0.54570929j, 0.30338582+0.95320164j],
        [0.28875044+0.86378946j, 0.93382112+0.68304046j,
         0.67551711+0.20267344j, 0.67804693+0.55437023j]],

       [[0.00166336+0.47209283j, 0.78501764+0.12603527j,
         0.20356871+0.38467759j, 0.20376949+0.62047884j],
        [0.1565408 +0.53002838j, 0.90173017+0.768874j  ,
         0.45178376+0.08940618j, 0.39414042+0.33538903j],
        [0.57309486+0.36304056j, 0.55059401+0.93405582j,
         0.08533191+0.62301052j, 0.0559353 +0.03335903j]]])

## Permute and Reshape Operations

In [6]:
# transpose
A = np.random.rand(2,3,2,3)
A_t = np.transpose(A, (3,0,1,2))

display(A)
display(A_t)

array([[[[0.38271545, 0.57061224, 0.10311888],
         [0.47253968, 0.25130776, 0.34458012]],

        [[0.99329662, 0.21963558, 0.37413501],
         [0.09722939, 0.91440703, 0.17703194]],

        [[0.44189682, 0.95205991, 0.7981916 ],
         [0.09697487, 0.04034037, 0.42543812]]],


       [[[0.97568582, 0.26510708, 0.38599855],
         [0.75773775, 0.15417676, 0.96959754]],

        [[0.46140605, 0.01569292, 0.34646096],
         [0.90398544, 0.83066175, 0.61064611]],

        [[0.34354554, 0.94774557, 0.05806953],
         [0.96000626, 0.1190856 , 0.9123129 ]]]])

array([[[[0.38271545, 0.47253968],
         [0.99329662, 0.09722939],
         [0.44189682, 0.09697487]],

        [[0.97568582, 0.75773775],
         [0.46140605, 0.90398544],
         [0.34354554, 0.96000626]]],


       [[[0.57061224, 0.25130776],
         [0.21963558, 0.91440703],
         [0.95205991, 0.04034037]],

        [[0.26510708, 0.15417676],
         [0.01569292, 0.83066175],
         [0.94774557, 0.1190856 ]]],


       [[[0.10311888, 0.34458012],
         [0.37413501, 0.17703194],
         [0.7981916 , 0.42543812]],

        [[0.38599855, 0.96959754],
         [0.34646096, 0.61064611],
         [0.05806953, 0.9123129 ]]]])

In [8]:
# reshape

B = np.random.rand(4,4,4)
B_r = np.reshape(B, (4,4**2))

display(B)
display(B_r)

array([[[0.27747276, 0.93008444, 0.70563852, 0.49475151],
        [0.62283996, 0.24690944, 0.11299233, 0.98942577],
        [0.32682595, 0.36370959, 0.44303925, 0.97334583],
        [0.94582697, 0.07368258, 0.44195251, 0.48934515]],

       [[0.8103584 , 0.95482839, 0.97597424, 0.87885032],
        [0.36494253, 0.63963669, 0.62484613, 0.84424054],
        [0.38853608, 0.50352933, 0.17763602, 0.61273888],
        [0.61309569, 0.22415198, 0.7651921 , 0.50906255]],

       [[0.79466681, 0.74809981, 0.11166827, 0.16517512],
        [0.22439129, 0.68767109, 0.69845586, 0.05997296],
        [0.66088796, 0.13111013, 0.29817523, 0.05221227],
        [0.27383055, 0.91811058, 0.08194744, 0.7112816 ]],

       [[0.9107781 , 0.03907445, 0.53872707, 0.83576443],
        [0.66162201, 0.3524877 , 0.48660547, 0.40318976],
        [0.87406861, 0.99532051, 0.29808714, 0.8702461 ],
        [0.67866806, 0.56893313, 0.25400262, 0.75206961]]])

array([[0.27747276, 0.93008444, 0.70563852, 0.49475151, 0.62283996,
        0.24690944, 0.11299233, 0.98942577, 0.32682595, 0.36370959,
        0.44303925, 0.97334583, 0.94582697, 0.07368258, 0.44195251,
        0.48934515],
       [0.8103584 , 0.95482839, 0.97597424, 0.87885032, 0.36494253,
        0.63963669, 0.62484613, 0.84424054, 0.38853608, 0.50352933,
        0.17763602, 0.61273888, 0.61309569, 0.22415198, 0.7651921 ,
        0.50906255],
       [0.79466681, 0.74809981, 0.11166827, 0.16517512, 0.22439129,
        0.68767109, 0.69845586, 0.05997296, 0.66088796, 0.13111013,
        0.29817523, 0.05221227, 0.27383055, 0.91811058, 0.08194744,
        0.7112816 ],
       [0.9107781 , 0.03907445, 0.53872707, 0.83576443, 0.66162201,
        0.3524877 , 0.48660547, 0.40318976, 0.87406861, 0.99532051,
        0.29808714, 0.8702461 , 0.67866806, 0.56893313, 0.25400262,
        0.75206961]])

**Permute** function reorders the storage of the element of a tensor in computer memory, this incurs some computational costs. In contrast **reshape** function leaves the element of a tensor unchanged in memory, instead only changing the metadata for how the tensor is to be interpreted and this incurs negligible cost.

## Binary Tensor Contractions

In [11]:
# binary tensor contraction 

d = 2
A = np.random.rand(d,d,d,d)
B = np.random.rand(d,d,d,d)
print("Initial Tensors")
display(A)
display(B)
Ap = A.transpose(0,2,1,3)
Bp = B.transpose(0,3,1,2)
print("Permuted Tensors")
display(Ap)
display(Bp)

App = Ap.reshape(d**2,d**2)
Bpp = Bp.reshape(d**2,d**2)
print("Reshaped Tensors")
display(App)
display(Bpp)

Cpp = App @ Bpp
print("Contraction")
display(Cpp)

C = Cpp.reshape(d,d,d,d)
print("Final Tensor")
display(C)



Initial Tensors


array([[[[0.14966176, 0.04441784],
         [0.26109767, 0.26459875]],

        [[0.87701569, 0.96562494],
         [0.92137519, 0.35467233]]],


       [[[0.09697167, 0.78108545],
         [0.71361345, 0.193128  ]],

        [[0.61910963, 0.08305442],
         [0.90326239, 0.47252984]]]])

array([[[[0.47077855, 0.83717205],
         [0.99021182, 0.47997853]],

        [[0.24399811, 0.88553652],
         [0.172658  , 0.0731465 ]]],


       [[[0.16891504, 0.7372255 ],
         [0.10819388, 0.92345101]],

        [[0.01786444, 0.97834993],
         [0.90950649, 0.21898465]]]])

Permuted Tensors


array([[[[0.14966176, 0.04441784],
         [0.87701569, 0.96562494]],

        [[0.26109767, 0.26459875],
         [0.92137519, 0.35467233]]],


       [[[0.09697167, 0.78108545],
         [0.61910963, 0.08305442]],

        [[0.71361345, 0.193128  ],
         [0.90326239, 0.47252984]]]])

array([[[[0.47077855, 0.99021182],
         [0.24399811, 0.172658  ]],

        [[0.83717205, 0.47997853],
         [0.88553652, 0.0731465 ]]],


       [[[0.16891504, 0.10819388],
         [0.01786444, 0.90950649]],

        [[0.7372255 , 0.92345101],
         [0.97834993, 0.21898465]]]])

Reshaped Tensors


array([[0.14966176, 0.04441784, 0.87701569, 0.96562494],
       [0.26109767, 0.26459875, 0.92137519, 0.35467233],
       [0.09697167, 0.78108545, 0.61910963, 0.08305442],
       [0.71361345, 0.193128  , 0.90326239, 0.47252984]])

array([[0.47077855, 0.99021182, 0.24399811, 0.172658  ],
       [0.83717205, 0.47997853, 0.88553652, 0.0731465 ],
       [0.16891504, 0.10819388, 0.01786444, 0.90950649],
       [0.7372255 , 0.92345101, 0.97834993, 0.21898465]])

Contraction


array([[0.9676674 , 1.15611152, 1.0362373 , 1.03819782],
       [0.76154148, 0.8127534 , 0.6614727 , 0.98009959],
       [0.86536186, 0.61460731, 0.80765693, 0.65514848],
       [0.99857092, 1.33341138, 0.82357804, 1.06233749]])

Final Tensor


array([[[[0.9676674 , 1.15611152],
         [1.0362373 , 1.03819782]],

        [[0.76154148, 0.8127534 ],
         [0.6614727 , 0.98009959]]],


       [[[0.86536186, 0.61460731],
         [0.80765693, 0.65514848]],

        [[0.99857092, 1.33341138],
         [0.82357804, 1.06233749]]]])