# T1.1 Diagrammatic Notation

Tensors are multi-dimensional arrays of real or complex numbers.

In [1]:
import numpy as np

# let's initalize some tensors

# tensor with randomly generated entries, order 3, dims 2x3x4
A = np.random.rand(2,3,4)

display(A)

# identity tensor, order 3, dims 3x3x3
I = np.eye(3)

display(I)

# identity matrix, order 2, dims: 5x5
B = np.eye(5,5)

display(B)

# tensor of 1s, order 4, dims 2x4x2x4
C = np.ones((2,4,2,4))

display(C)

# matrix of 0s, order 2, dims 3x5
D = np.zeros((3,5))

display(D)

# initialize complex random tensor
E = np.random.rand(2,3,4) + 1j*np.random.rand(2,3,4)

display(E)

array([[[0.20273949, 0.80778756, 0.31286692, 0.30857714],
        [0.41634756, 0.56085   , 0.26563361, 0.28810896],
        [0.53240077, 0.75132032, 0.4682209 , 0.70796967]],

       [[0.68013413, 0.56733917, 0.22889048, 0.5018115 ],
        [0.13364797, 0.27698234, 0.02343784, 0.43594217],
        [0.95119107, 0.66812444, 0.32599289, 0.31211439]]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[[0.13833212+0.87116431j, 0.46403917+0.60011631j,
         0.30230274+0.65852944j, 0.2219799 +0.72484696j],
        [0.10932178+0.89762038j, 0.27386036+0.10371121j,
         0.4765782 +0.45162285j, 0.65760932+0.30657603j],
        [0.163439  +0.60153655j, 0.64799939+0.15906163j,
         0.79989683+0.81697655j, 0.97108911+0.7899836j ]],

       [[0.02114424+0.55633792j, 0.11469286+0.27811851j,
         0.69948039+0.81017936j, 0.78284142+0.55593858j],
        [0.68596999+0.45516463j, 0.78789045+0.85416396j,
         0.34212002+0.81541375j, 0.19076582+0.61527253j],
        [0.01168475+0.9332669j , 0.16023504+0.36425927j,
         0.81257731+0.27881715j, 0.74272802+0.38868454j]]])

## Permute and Reshape Operations

In [2]:
# transpose
A = np.random.rand(2,3,2,3)
A_t = np.transpose(A, (3,0,1,2))

display(A)
display(A_t)

array([[[[0.22396195, 0.07721999, 0.5919378 ],
         [0.97349095, 0.29267059, 0.98572582]],

        [[0.75279041, 0.40805569, 0.64014793],
         [0.64094512, 0.03709634, 0.98067278]],

        [[0.24639044, 0.23435325, 0.74116796],
         [0.05752702, 0.10219759, 0.63606098]]],


       [[[0.48218389, 0.13397305, 0.20236062],
         [0.19352784, 0.8017409 , 0.47652709]],

        [[0.88126845, 0.39424727, 0.95676485],
         [0.83229795, 0.90396522, 0.207011  ]],

        [[0.86741719, 0.04064226, 0.51112982],
         [0.15757665, 0.02421379, 0.11027807]]]])

array([[[[0.22396195, 0.97349095],
         [0.75279041, 0.64094512],
         [0.24639044, 0.05752702]],

        [[0.48218389, 0.19352784],
         [0.88126845, 0.83229795],
         [0.86741719, 0.15757665]]],


       [[[0.07721999, 0.29267059],
         [0.40805569, 0.03709634],
         [0.23435325, 0.10219759]],

        [[0.13397305, 0.8017409 ],
         [0.39424727, 0.90396522],
         [0.04064226, 0.02421379]]],


       [[[0.5919378 , 0.98572582],
         [0.64014793, 0.98067278],
         [0.74116796, 0.63606098]],

        [[0.20236062, 0.47652709],
         [0.95676485, 0.207011  ],
         [0.51112982, 0.11027807]]]])

In [3]:
# reshape

B = np.random.rand(4,4,4)
B_r = np.reshape(B, (4,4**2))

display(B)
display(B_r)

array([[[3.86597036e-01, 6.94710533e-01, 8.24292665e-01, 1.29421968e-01],
        [4.27609941e-01, 3.80803835e-01, 4.27401576e-01, 2.05752476e-01],
        [5.87131111e-01, 3.22363484e-01, 3.57179129e-01, 9.19805714e-01],
        [3.11623194e-01, 3.00379633e-01, 4.21283502e-01, 2.71864047e-04]],

       [[4.97943635e-02, 9.46762921e-01, 9.59193782e-01, 1.53611833e-01],
        [4.82139294e-02, 2.26444650e-01, 3.10945487e-01, 6.71434041e-01],
        [5.53126056e-01, 2.24180837e-01, 3.29831413e-01, 1.83358060e-01],
        [1.37115157e-01, 7.25152806e-01, 6.28989539e-01, 8.46968563e-01]],

       [[3.67756910e-01, 6.56191126e-01, 3.65699356e-02, 5.52350533e-01],
        [8.15985509e-01, 3.54029353e-02, 7.96109842e-01, 2.25755333e-01],
        [8.60774979e-01, 2.43528537e-01, 1.32254992e-01, 2.68790872e-01],
        [3.59150302e-01, 5.36622311e-01, 2.75931633e-01, 3.83073040e-01]],

       [[7.53945780e-02, 3.40808416e-01, 3.53681440e-03, 9.15029740e-01],
        [6.01040791e-01, 2.98721

array([[3.86597036e-01, 6.94710533e-01, 8.24292665e-01, 1.29421968e-01,
        4.27609941e-01, 3.80803835e-01, 4.27401576e-01, 2.05752476e-01,
        5.87131111e-01, 3.22363484e-01, 3.57179129e-01, 9.19805714e-01,
        3.11623194e-01, 3.00379633e-01, 4.21283502e-01, 2.71864047e-04],
       [4.97943635e-02, 9.46762921e-01, 9.59193782e-01, 1.53611833e-01,
        4.82139294e-02, 2.26444650e-01, 3.10945487e-01, 6.71434041e-01,
        5.53126056e-01, 2.24180837e-01, 3.29831413e-01, 1.83358060e-01,
        1.37115157e-01, 7.25152806e-01, 6.28989539e-01, 8.46968563e-01],
       [3.67756910e-01, 6.56191126e-01, 3.65699356e-02, 5.52350533e-01,
        8.15985509e-01, 3.54029353e-02, 7.96109842e-01, 2.25755333e-01,
        8.60774979e-01, 2.43528537e-01, 1.32254992e-01, 2.68790872e-01,
        3.59150302e-01, 5.36622311e-01, 2.75931633e-01, 3.83073040e-01],
       [7.53945780e-02, 3.40808416e-01, 3.53681440e-03, 9.15029740e-01,
        6.01040791e-01, 2.98721623e-01, 2.30291232e-01, 1.546

**Permute** function reorders the storage of the element of a tensor in computer memory, this incurs some computational costs. In contrast **reshape** function leaves the element of a tensor unchanged in memory, instead only changing the metadata for how the tensor is to be interpreted and this incurs negligible cost.

## Binary Tensor Contractions

In [4]:
# binary tensor contraction 

d = 2
A = np.random.rand(d,d,d,d)
B = np.random.rand(d,d,d,d)
print("Initial Tensors")
display(A)
display(B)
Ap = A.transpose(0,2,1,3)
Bp = B.transpose(0,3,1,2)
print("Permuted Tensors")
display(Ap)
display(Bp)

App = Ap.reshape(d**2,d**2)
Bpp = Bp.reshape(d**2,d**2)
print("Reshaped Tensors")
display(App)
display(Bpp)

Cpp = App @ Bpp
print("Contraction")
display(Cpp)

C = Cpp.reshape(d,d,d,d)
print("Final Tensor")
display(C)



Initial Tensors


array([[[[0.7371058 , 0.05982483],
         [0.61400774, 0.5423446 ]],

        [[0.72944939, 0.95116359],
         [0.06606588, 0.8757056 ]]],


       [[[0.61417943, 0.21567681],
         [0.92563128, 0.16441288]],

        [[0.12407705, 0.34614424],
         [0.9486919 , 0.62908703]]]])

array([[[[0.54726949, 0.54872276],
         [0.36547486, 0.40368657]],

        [[0.89075655, 0.7909781 ],
         [0.55277609, 0.55662475]]],


       [[[0.16804915, 0.28968501],
         [0.21273445, 0.07305388]],

        [[0.16628066, 0.96532904],
         [0.99188843, 0.02140442]]]])

Permuted Tensors


array([[[[0.7371058 , 0.05982483],
         [0.72944939, 0.95116359]],

        [[0.61400774, 0.5423446 ],
         [0.06606588, 0.8757056 ]]],


       [[[0.61417943, 0.21567681],
         [0.12407705, 0.34614424]],

        [[0.92563128, 0.16441288],
         [0.9486919 , 0.62908703]]]])

array([[[[0.54726949, 0.36547486],
         [0.89075655, 0.55277609]],

        [[0.54872276, 0.40368657],
         [0.7909781 , 0.55662475]]],


       [[[0.16804915, 0.21273445],
         [0.16628066, 0.99188843]],

        [[0.28968501, 0.07305388],
         [0.96532904, 0.02140442]]]])

Reshaped Tensors


array([[0.7371058 , 0.05982483, 0.72944939, 0.95116359],
       [0.61400774, 0.5423446 , 0.06606588, 0.8757056 ],
       [0.61417943, 0.21567681, 0.12407705, 0.34614424],
       [0.92563128, 0.16441288, 0.9486919 , 0.62908703]])

array([[0.54726949, 0.36547486, 0.89075655, 0.55277609],
       [0.54872276, 0.40368657, 0.7909781 , 0.55662475],
       [0.16804915, 0.21273445, 0.16628066, 0.99188843],
       [0.28968501, 0.07305388, 0.96532904, 0.02140442]])

Contraction


array([[0.83434395, 0.51820933, 1.7433811 , 1.18464595],
       [0.89840563, 0.52136981, 1.83224364, 0.72556518],
       [0.57559228, 0.36321562, 1.07245468, 0.59003436],
       [0.9384508 , 0.65244294, 1.71958421, 1.55764487]])

Final Tensor


array([[[[0.83434395, 0.51820933],
         [1.7433811 , 1.18464595]],

        [[0.89840563, 0.52136981],
         [1.83224364, 0.72556518]]],


       [[[0.57559228, 0.36321562],
         [1.07245468, 0.59003436]],

        [[0.9384508 , 0.65244294],
         [1.71958421, 1.55764487]]]])